
#ifndef  _PCITESTERRNO_H
#define  _PCITESTERRNO_H


#define PCIERR_DM_OPENDEVICE				0x01
#define PCIERR_DM_OPENSESSION				0x02
#define PCIERR_DM_GENRANDOM				0x03
#define PCIERR_DM_RANDOMEQUAL				0x04
#define PCIERR_DM_CLOSESESSION				0x05
#define PCIERR_DM_CLOSEDEVICE				0x06
#define PCIERR_DM_GETDEVICEINFO				0x07
#define PCIERR_DM_GETPRIKEYACCESSRIGHT			0x08
#define PCIERR_DM_RELEASEPRIKEYACCESSRIGHT		0x09

#define PCIERR_NKM_EXPORTSIGNPUBKEY			0x0a
#define PCIERR_NKM_EXPORTENCRYPTPUBKEY			0x0b
#define PCIERR_NKM_GENERATEKEYWITHKEK			0x0c
#define PCIERR_NKM_IMPORTKEYWITHKEK			0x0d
#define PCIERR_NKM_GENERATEKEYWITHECC			0x0e
#define PCIERR_NKM_IMPORTKEYWITHECC			0x0f
#define PCIERR_NKM_DESTROYKEY				0x10

#define PCIERR_CKM_GENERATEKEYMATRIX			0x11
#define PCIERR_CKM_GENERATECENTERKEY			0x12
#define PCIERR_CKM_GENERATEKEK				0x13
#define PCIERR_CKM_DELETEKEK				0x14
#define PCIERR_CKM_IMPORTPUBMATRIX			0x15
#define PCIERR_CKM_EXPORTPUBMATRIX			0x16
#define PCIERR_CKM_SEGMENTKEY				0x17
#define PCIERR_CKM_GETSEGMENTKEY			0x18
#define PCIERR_CKM_KEYRECOVERYINIT			0x19
#define PCIERR_CKM_IMPORTSEGMENTKEY			0x1a
#define PCIERR_CKM_KEYRECOVERY				0x1b
#define PCIERR_CKM_IMPORTENVELOPE			0x1c
#define PCIERR_CKM_EXPORTENVELOPE			0x1d

#define PCIERR_DI_SM3					0x1e
#define PCIERR_DI_HASHINIT				0x1f
#define PCIERR_DI_HASHUPDATE				0x20
#define PCIERR_DI_HASHFINAL				0x21

#define PCIERR_SM_ENCRYPTINIT				0x22
#define PCIERR_SM_ENCRYPTUPDATE				0x23
#define PCIERR_SM_ENCRYPTFINAL				0x24
#define PCIERR_SM_DECRYPTINIT				0x25
#define PCIERR_SM_DECRYPTUPDATE				0x26
#define PCIERR_SM_DECRYPTFINAL				0x27
#define PCIERR_SM_DECRYPTFAIL				0x28
#define PCIERR_SM_MACINIT				0x29
#define PCIERR_SM_MACUPDATE				0x2a
#define PCIERR_SM_MACFINAL				0x2b

#define PCIERR_FL_CREATFILE				0x2c
#define PCIERR_FL_WRITEFILE				0x2d
#define PCIERR_FL_READFILE				0x2e
#define PCIERR_FL_DELETEFILE				0x2f

#define PCIERR_ASM_ECCSIGN				0x30
#define PCIERR_ASM_ECCVERIFY				0x31

#define PCIERR_CKM_CALCULATESERVERKEY			0x32
#define PCIERR_ASM_INTERNALVERIFY			0x33
#define PCIERR_ASM_EXTERNALENCRYPT			0x34
#define PCIERR_NKM_GENAGREEDATAWITHECC			0x35
#define PCIERR_NKM_GENAGREEMENTDATAANDKEYWITHECC	0x36
#define PCIERR_NKM_GENKEYWITHECC			0x37
#define PCIERR_SM_ENCRYPT				0x38
#define PCIERR_SM_DECRYPT				0x39
#define PCIERR_NKM_KEYEXCHANGE				0x3a
#define PCIERR_NKM_GENECCKEYPAIR			0x3b
#define PCIERR_NKM_ExchangeDigitEnv			0x3c


//APP
#define PCIERR_APP_OPENDEV				0x40
#define PCIERR_APP_CLOSEDEV				0x41
#define PCIERR_APP_GENERATEMATRIX			0x42
#define PCIERR_APP_GETDEVINFO				0x43
#define PCIERR_APP_GETHANDLE				0x44
#define PCIERR_APP_IMPORTMATRIX				0x45
#define PCIERR_APP_EXPORTMATRIX				0x46
#define PCIERR_APP_CALCULATEDEVKEY			0x47
#define PCIERR_APP_GENERATECENTERKEY			0x48
#define PCIERR_APP_CALCULATESERVERKEY			0x49
#define PCIERR_APP_SM3					0x4a
#define PCIERR_APP_SIGN					0x4b
#define PCIERR_APP_VERIFY				0x4c
#define PCIERR_APP_ENCRYPT				0x4d
#define PCIERR_APP_DECRYPT				0x4e
#define PCIERR_APP_CALCULATEPERSONKEY			0x4f
#define PCIERR_APP_IMPORTDEVENVELOPE			0x50
#define PCIERR_APP_EXPORTDEVENVELOPE			0x51
#define PCIERR_APP_IMPORTSERVERKEY			0x52
#define PCIERR_APP_VERIFYPIN				0x53
#define PCIERR_APP_CALCULATEPUBKEY			0x54


#endif  
